name: .NET Core Desktop
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
    runs-on: windows-latest
    env:
      Solution_Name: ClassLibrary2.sln
      Test_Project_Path: ClassLibrary2/ClassLibrary2.csproj
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ClassLibrary2.sln # Явно восстанавливаем зависимости
      - name: Build
        run: dotnet build ClassLibrary2.sln --configuration Debug --no-restore
      - name: Execute unit tests
        run: dotnet test ClassLibrary2.sln --configuration Debug --no-restore
